version: '3.5'

services:
  hh_rest_server:
    image: 'hh_rest_server:latest'
    build:
      context: .
    container_name: hh_rest_server
    depends_on:
      - mongo_db
    ports:
      - "8080:8080"

  mongo_db:
    image: 'mongo:4.4.3'
    restart: always
    ports:
      - "27017:27017"